### ISSUE TITLE
Message edits are not displayed

### ISSUE THREAD

**Issue by Ppjet6** [42wim/matterircd#106]
## Steps to reproduce

- Connect to mattermost via matterircd
- Send a message from the mattermost side
- Edit the message from the same side

## What happens

No mention of the edit is made.

## What I expect

Maybe it would be possible to just display the edited message after the first one. That's what happens usually on XMPP->IRC when [Last Message Correction](https://xmpp.org/extensions/xep-0308.html) is used.
With mattermost it seems to be possible to edit messages way further than the last one, so maybe have something just like comments `(edit<n>)` or `(edited: <message>)`
Is this maybe another limitation? I haven't looked at mattermost closely enough

**Comment by Ppjet6** [comment]
I just realized edits do appear just as I suggested, for the _last_ message only. Do you think there is a way to do more?

**Comment by 42wim** [comment]
Could you give an example what you mean ?
It relays any messages you edit, regardless of the time it was created.

**Comment by Ppjet6** [comment]
Here apparently I only get the edits if it's the last message. Maybe it's my client then? I'm using irssi 1.0.2

**Comment by 42wim** [comment]
No, shouldn't be client side (using irssi also).
Try running with debug and see if you get a post_edited event for each edit
```
WsReceiver event: model.WebSocketEvent{Event:"post_edited", ...
```
What version of mattermost ?

**Comment by jmallach** [comment]
Hi @42wim! Mattermost is 3.10.

**Comment by 42wim** [comment]
@Ppjet6 or @jmallach  Could you paste debug logs when trying to edit ?

**Comment by 42wim** [comment]
Also an "(edited) " message is now added to edited messages

**Comment by epatpol** [comment]
Hey I noticed that some very cool features were added when I last updated matterircd today (the replies are particularly welcome!). Edits look pretty cool but they do not seem to be working for me, i.e if someone edits a message saying "test" with "test2" I get the following:

`
(edited) test2
(edited) test2
`

I would assume that the first one is supposed to be the old message and the second one is supposed to be the new message right? Otherwise that doesn't really make sense.

I'm on mm Version: 4.0.0  (4.0.1) and the latest matterircd image from dockerhub (not sure if I can be more specific about this one, the digest maybe?)

`
sing default tag: latest
latest: Pulling from 42wim/matterircd
Digest: sha256:840d3f7a189520dbcfa3dd94065883e13c09abce80f294f2ca89f3538cd587b2
Status: Image is up to date for 42wim/matterircd:latest
`
Not sure if this belongs here, or should be in a new issue, I'll create another issue if needed.

Thanks!

**Comment by Ppjet6** [comment]
Yes I am also seeing edited messages double.

> @Ppjet6 or @jmallach Could you paste debug logs when trying to edit ?

Sorry for never providing any, I need to try and run the gateway in debug mode, will try that soon.

**Comment by 42wim** [comment]
Ok, it seems like the double edited messages is a mattermost 4.0.x bug, they're sending edited messages double. I've fixed this in matterbridge by using a cache and going to add it here too.

**Comment by 42wim** [comment]
Should be fixed now in master
@Ppjet6 I guess you're upgraded to mattermost 4.x ? Could you rebuild from master and try ?
@epatpol I've updated the dockerhub image with the fix, can you try ?

**Comment by epatpol** [comment]
Yep just tested with the new dockerhub image and it works fine (no more double edited messages)

Thanks @42wim !
