### ISSUE TITLE
Close window without leaving channel

### ISSUE THREAD

**Issue by tim0s** [42wim/matterircd#133]
Is it possible to close a window in IRC but not leave the channel? My mattermost instance has a lot of channels, leading to a large number of windows in irssi, so it becomes hard to find the "important" ones. If I do a /wc on an "unimportant" channel I leave that channel automatically and someone needs to invite me back in, I would prefer if window-closing in irssi would have zero effects on mattermost. Maybe this can be made a configuration option?

**Comment by 42wim** [comment]
Yes that's annoying, but there is currently no way to do this.

Matterircd is supposed to be a 1:1 mapping of the same channels as mattermost, so if you decide to leave a channel, this also happens on mattermost. 

Matterircd asks the state of the user to mattermost to decide in which channels a user is supposed to be.

What would happen if someone says something to you in the unimportant channel ? Or if someone removes you from the unimportant channel.

It's not so easy to add support for this because all of the possible issues, but I'm open for PR's for this.
(I don't have any time shortterm for this)

**Comment by 42wim** [comment]
This is now possible in master, you'll have to create a matterircd.toml file with `PartFake=true` in it.
And run `matterircd -conf matterircd.toml`

See https://github.com/42wim/matterircd/blob/master/matterircd.toml.example for more info
