### ISSUE TITLE
Own messages not synced between IRC and web interface

### ISSUE THREAD

**Issue by tgr** [42wim/matterircd#14]
I joined http://mattermost.wmflabs.org/wikimedia/channels/town-square in the browser and ran `/server matterirc.wmflabs.org` and ran `/msg mattermost LOGIN XXX XXXXX` in the IRC client (and got a `login OK` response). After that, I could chat with the other person on the channel and he saw my messages instantly, whether I typed them on IRC or in the browser, and I saw his messages on both interfaces; but I my own messages that I typed on IRC didn't show up in the web browser, and the ones typed in the browser did not show up in the IRC client.

After a while, I got the message `-!- Irssi: Join to #town-square was synced in 561 secs` on IRC; after that, messages I wrote on IRC appeared on the web interface (both new ones and the previous ones retroactively), but the other direction continued not to work.

**Comment by 42wim** [comment]
Regarding the part from your issue: "ones typed in the browser did not show up in the IRC client"
This is by "design", your own messages are ignored (it works in the same way as eg bitlbee). 

Otherwise all your messages will be echoed on IRC, because there is no way to know if the message you send came from IRC or came from the web browser (or from any other client). 

The other issue:
Typing in IRC and not showing up in the web interface seems like a bug. 
But it worked for a while, then stopped working and started working again after the synced message ? correct ?

**Comment by 42wim** [comment]
If you rebuild from master, the irssi syncing message should also be < 1 minute now. Implemented the MODE questions that irssi asks. Doubt that they're relevant to the bug though.

**Comment by tgr** [comment]
> But it worked for a while, then stopped working and started working again after the synced message ? correct ?

It did not work initially and only started working after the sync message. I tried to reproduce it now after disconnecting and reconnecting, but couldn't.

**Comment by yuvipanda** [comment]
(I'll update from master again later today)

**Comment by yuvipanda** [comment]
(I updated our matterircd instance to latest master btw)

**Comment by yuvipanda** [comment]
Ok, so @bd808 also confirms that the messages from web don't echo back to IRC, but it does work when ZNC is connected to freenode. I think ZNC deals with it by keeping track of what messages were said by which client and echoing it back to all other clients. Can we do that too? i.e. find some way of keeping track of which messages were sent out via the IRC bridge and which weren't...

**Comment by 42wim** [comment]
ZNC doesn't have to work with 2 clients with the same identity, who can send messages from different systems. :-)

Can't be done easily, irc messages have no identifier to them. That means we should compare whole sentences/strings.  

Also gives rise to issues like how should you handle if a message from mattermost is the same as the one you send from irc. 

A possible option would be to use a secret unicode invisible identifier that get send by every IRC message, and thus can be checked. As long as mattermost doesn't filter those.

**Comment by 42wim** [comment]
Ok, "fixed" this using an invisible space. (http://www.fileformat.info/info/unicode/char/180e/fontsupport.htm)

Only works with channels, not direct/private messages because of the IRC format, I can't spoof the IRC user in a direct/private message

**Comment by justjanne** [comment]
> Can't be done easily, irc messages have no identifier to them. That means we should compare whole sentences/strings. 

This is actually wrong.

The IRCv3 RFC clearly specifies a way to attach a tag to an irc message, it is used as replacement for `\x01ACTION\x01`, for example.

**Comment by 42wim** [comment]
Do you mean http://ircv3.net/specs/core/message-tags-3.2.html ? 

This wouldn't work because mattermost doesn't understand those tags. The problem is that mattermost sends a message back and we have to know if the message originated from mattermost or from IRC.

This only works if I can send a tag to mattermost telling it the message came from IRC and mattermost sends that tag back, I know it's a message from IRC. 

For now, this is emulated with a "for most people" invisible tag.

**Comment by kaniini** [comment]
Use `\x02\x02` at the end as a sentinel.
