### ISSUE TITLE
Feature Request: Support regular (non-mattermost) IRC channels for non-registered users

### ISSUE THREAD

**Issue by dgruss** [42wim/matterircd#170]
It would be great to have something like a guest channel (or multiple) for external people who are not registered mattermost users but only visitors.
This could be for instance be a support chat for a product that is maintained by the registered mattermost users.
If the team already uses matterircd anyway, this would be an easy way to provide such a support chat.

From the code it doesn't look like much work to implement it.
Are there any plans in that direction, or, if I spend time implementing it, would such a feature be merged, if properly implemented?

**Comment by 42wim** [comment]
Just to be clear, the idea is that the guest channel will be relayed to a mattermost channel ?
The problem here is going to be how to map those visitors to real mattermost users.

**Comment by dgruss** [comment]
I was originally thinking of a non-linked irc-only channel.
But even having a bot mirroring the visitors into an actual mattermost channel should be quite easy I think...

**Comment by 42wim** [comment]
Depends, public messages is easy, private messages is harder (because 1:1 mapping)

Anyway, if you just want to do a non-linked irc-only channel. 
I'll gladly merge this if you make it optional (extra setting in matterircd.toml to enable it). 

Some things to think about:
- The current default setting is that every user that connects is in his own server and can't interact with other users. Because of security/privacy, you don't want a random user to have access to your mattermost/slack conversations
- They can't join any IRC channels before they're logged in to mattermost or slack because of possible clashes with existing channels on mattermost/slack. So maybe you could use &channels or ##channels so that there are no clashes.

**Comment by 42wim** [comment]
closing because no further activity
