### ISSUE TITLE
Strange messages displayed alongside actions

### ISSUE THREAD

**Issue by uchwings** [42wim/matterircd#198]
When a user joins a Slack channel, I see two IRC lines of the following form:
```
* userfoo has joined #my-chan.
<userfoo> @ has joined the channel
```
The first of these is an IRC `JOIN` message as expected, but the second is a `PRIVMSG` that seems to be synthesized by matterircd. This second message is redundant and misleading, since the JOIN line contains the same information and userfoo never typed "@ has joined the channel".

**Comment by 42wim** [comment]
No, it's not synthesized by matterircd, slack sent this message everytime a user joins.
The `@` seems a bug though

**Comment by 42wim** [comment]
I'll see if I can surpress the "has joined" message

**Comment by liskin** [comment]
The `@` also sometimes happens when one user mentions another, as in:

`16:11:02 < hanule:#general> @ I can take it for you, leaving Saturday :slightly_smiling_face:`
instead of
`16:11:02 < hanule:#general> @Sheila I can take it for you, leaving Saturday :slightly_smiling_face:`

I haven't recognized any pattern in it yet, though. :-/
