### ISSUE TITLE
messages posted by webhook bots (ie, matterbridge) show as the bot user

### ISSUE THREAD

**Issue by RangerRick** [42wim/matterircd#37]
I have matterbridge configured to bridge between the #opennms channel on freenode and a channel on my mattermost server using webhooks.  When it proxies posts from IRC to mattermost, it sets the user to `irc-<username>` in the mattermost display, but when those same posts show up in matterircd, they show as coming from the username the webhook is registered as.

Is it possible to use the "display name" that the webhook is using as the username shown in matterircd?

**Comment by RangerRick** [comment]
Freenode IRC side:
<img width="665" alt="screen shot 2016-03-18 at 10 40 17 am" src="https://cloud.githubusercontent.com/assets/89252/13881082/db7bf1b0-ecf5-11e5-9b1f-1a5a50b0786d.PNG">

mattermost side:
<img width="438" alt="screen shot 2016-03-18 at 10 41 19 am" src="https://cloud.githubusercontent.com/assets/89252/13881117/fd7b383e-ecf5-11e5-9536-fa87ededbf79.PNG">

matterircd side:
<img width="548" alt="screen shot 2016-03-18 at 10 40 26 am" src="https://cloud.githubusercontent.com/assets/89252/13881086/df823152-ecf5-11e5-8c2c-ddaf3d46f413.PNG">

**Comment by 42wim** [comment]
Ok interesting problem :) Fixed it locally, going to push it in a minute.

If you want to test it you'll need a current mattermost server because they changed a session cookie.

If you want to test it against your current, 1.4+ then you'll have to modify locally in your GOPATH this file https://github.com/mattermost/platform/blob/master/model/session.go#L12 and change MMAUTHTOKEN to MMTOKEN

**Comment by RangerRick** [comment]
Sorry, just having a chance to look at this.  So you mean I have to modify it for MM 2.1?  ie, they changed the token in MM master post-2.1?

**Comment by 42wim** [comment]
correct
