### ISSUE TITLE
Tutorial for a working matteircd example using docker images

### ISSUE THREAD

**Issue by tuxdna** [42wim/matterircd#38]
I used Docker images on a Fedora 23 x64 machine:

```
docker pull mattermost/platform
docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform
```

Visit the address [http://localhost:8065/](http://localhost:8065/) then

 * create an account `hello@example.com` ( user `hello` , and password `hello` ), 
 * and also an organization named `temporary`

```
docker run -d -p 6667:6667 --name ircd xyproto/matterircd -mmserver localhost -mmteam temporary -interface 0.0.0.0
```

Then opened IRC client ( e.g. xchat ), and in an new server tab and enter:

```
/server localhost
```

This connecs to the matterircd IRC server, and login:

```
/msg mattermost login hello hello
LOGIN hello@localhost hello
```

Next step fails:

`/j #town-square `  for which I get `Cannot join join (Channel is invite only)`

This seems to connect and refuse, but not yet fully working.

I think there needs to be a working demo example using Docker images. That will enable someone to evaluate IRC integration.

**Comment by 42wim** [comment]
Mattermost is a fast-moving target lots of internal changes that breaks older versions of matterircd. 
The matterircd docker image also doesn't seem to be up to date.

But you can get it running if you fix your setup.

* Mattermost must run on port 80 (if using http), or 443 (if using https), matterircd has no support for other ports yet. And you must specify version 2.0

```docker run --name mattermost-dev -d --publish 80:80 mattermost/platform:2.0```

* Because you're running http you need the -mminsecure parameter. Also the -mmserver is not localhost because that will try to connect to the inside of the docker container. You'll need to specify to ip address of your docker host. So change -mmserver 1.2.3.4 to your ip. Also specify -debug so you can get more information what went wrong.

```docker run -d -p 6667:6667 --name ircd xyproto/matterircd -mmserver 1.2.3.4 -mmteam temporary -interface 0.0.0.0 -mminsecure -debug```

If you follow this, it should work. 

Any tutorial, maybe by combining your and mine posts is welcome :-)

**Comment by maxandersen** [comment]
Made this: https://github.com/maxandersen/mattermost-ircd-example

**Comment by tuxdna** [comment]
@maxandersen +1

**Comment by tuxdna** [comment]
The tutorial from @maxandersen  works! I think we can close this issue now.

**Comment by 42wim** [comment]
@maxandersen Would you mind adding your information to https://github.com/42wim/matterircd/wiki ?

**Comment by maxandersen** [comment]
did a quick'n'dirty copy/paste of the info.

**Comment by 42wim** [comment]
Thanks!
