### ISSUE TITLE
Password logging

### ISSUE THREAD

**Issue by keachi** [42wim/matterircd#73]
If matterircd is started in debug mode, all login passwords get plaintext logged. IMHO is this a really bad idea.
I think such private messages can be easily filtered, and displayed like the following:

```
Sep 15 08:23:59 hostname matterircd-linux64[9050]: time="2016-09-15T08:23:59+02:00" level=debug msg="<- PRIVMSG mattermost :login user1 <filtered>" module=matterircd
```

Without such a filter, you should never run the matterircd on a productive system with debug enabled.

**Comment by 42wim** [comment]
Good point, I'll add this.
But running matterircd in production with debug isn't advised because of the overhead that debugs gives on busy systems.

**Comment by 42wim** [comment]
If anyone has time to do this, PR's are welcome.

**Comment by slowbro** [comment]
I'd be happy to do this, but i'm having trouble figuring out the 'best' way - here are my ideas so far.

1. Parse for a message that looks like 'PRIVMSG <anything> :login' and truncate it after 'login' (hiding username & password)
a. this seems kind of hacky and coudl match other things?
2. Move logging out of user.Decode() and make it more granular?
a. but then you have a lot of repeated code, and there's also the possibility that something gets missed in the future (i.e. forgot to add the debug line)
3. Abandon this change - as @42wim said, you really should not be running this with -debug in production, and debug logs always are inherently 'insecure' as you are dumping as much information as possible.

Input would be appreciated.

**Comment by 42wim** [comment]
@slowbro thanks for taking an interest :)
If you want to spend time on this it's very much appreciated!

I would take option 1 for this and do the check user.Decode()

Check if privmsg to mattermost or slack is sent, use the function on https://github.com/42wim/mm-go-irckit/blob/master/mmservice.go#L291 to parse the line, so you can also match long passwords.
Also take a look at https://github.com/42wim/mm-go-irckit/blob/master/mmservice.go#L93-L111 because the login command can have different amount of parameters depending on the options passed.

Maybe refactor those L93-L111 in a function that can be reused for your check.

**Comment by slowbro** [comment]
Understood! I will start work on this.

**Comment by slowbro** [comment]
Created a PR. I ended up not using `parseCommandString` since the fixes for non-rfc (i.e. missing  `:`) come later.. this seemed like the most straightforward way to accomplish it.

Let me know if you want anything changed!
